"""The operations every caller shares: search, open, download, credits.

The UI routes and the agent tools in service.py are thin adapters over these
functions, so a person browsing and an agent searching always see the same
library, ranking, licence data and import notes.

Sounds come live from Freesound when the owner has connected a key: sound
searches go to Freesound, other searches get its match count, and a search
that finds nothing locally falls back to Freesound sounds.
"""
from __future__ import annotations

import json
import os
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from . import catalog, credits, download, net, pace, resources, search
from .db import dumps, loads, now, transaction
from .importnotes import ENGINES, engine_id
from .sources import freesound, importer

GENERATED_MARK = '<!-- generated by Asset Commons -->'
KICK_EVERY_S = 120


class NotFound(Exception):
    pass


def kick_sync(db, *, force: bool = False) -> bool:
    """Ask Möbius to start the sync job (a no-op while it is already running).

    The job reads OpenGameArt entry pages in the background; this restarts it
    after the container restarted, and wakes it for an entry someone opened.
    """
    row = db.execute("SELECT value FROM meta WHERE key='sync_kicked_at'").fetchone()
    if row and not force and time.time() - float(row[0] or 0) < KICK_EVERY_S:
        return False
    base, token, app = (os.environ.get(k) for k in ('API_BASE_URL', 'APP_TOKEN', 'APP_ID'))
    if not (base and token and app):
        return False
    with transaction(db):
        db.execute("INSERT INTO meta (key, value) VALUES ('sync_kicked_at', ?) "
                   "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (str(time.time()),))
    request = urllib.request.Request(f'{base.rstrip("/")}/api/apps/{app}/run-job', data=b'{}', method='POST',
                                     headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(request, timeout=5):
            return True
    except Exception:  # noqa: BLE001 - best effort; the weekly schedule runs the job anyway
        return False


def crawl_progress(db) -> dict | None:
    """How far the background reading of OpenGameArt entry pages has got."""
    waiting = db.execute("SELECT COUNT(*) FROM crawl_queue WHERE source='opengameart'").fetchone()[0]
    row = db.execute("SELECT value FROM meta WHERE key='opengameart_progress'").fetchone()
    progress = loads(row[0], {}) if row else {}
    if not waiting and not progress:
        return None
    read = db.execute("SELECT COUNT(*) FROM assets WHERE source='opengameart' "
                      "AND json_extract(attributes, '$.details')='complete'").fetchone()[0]
    module = importer('opengameart')
    return {'waiting': waiting, 'read': read, 'phase': progress.get('phase'), 'updated_at': progress.get('at'),
            'hours_left': round(waiting * module.CRAWL_INTERVAL / 3600, 1) if waiting else 0}


def _stale(stamp: str | None, minutes: float) -> bool:
    try:
        then = datetime.fromisoformat(str(stamp).replace('Z', '+00:00'))
    except ValueError:
        return True
    return (datetime.now(timezone.utc) - then).total_seconds() > minutes * 60


def ensure_details(db, asset: dict, *, fetch: bool = True, max_age_days: float | None = None
                   ) -> tuple[dict, str | None, bool]:
    """Make sure an asset's details and file list are known: (asset, problem, pending).

    Sources read through a queue (OpenGameArt) read the entry page now when
    `fetch` is set (paced; an agent can wait); otherwise the entry moves to the
    front of the background queue and `pending` is True. Other sources list
    their files lazily (Poly Haven).
    """
    module = importer(asset['source'])
    if module is not None and hasattr(module, 'fetch_record') and asset.get('origin') == 'index':
        if not module.needs_details(asset, max_age_days):
            return asset, None, False
        name = credits.SOURCE_NAMES.get(asset['source'], asset['source'])
        if not fetch:
            module.request_details(db, asset['id'])
            kick_sync(db)
            return asset, None, True
        try:
            record, reason = module.fetch_record(asset)
        except pace.Busy:
            module.request_details(db, asset['id'])
            kick_sync(db)
            return asset, None, True
        except net.FetchError as exc:
            if exc.status in (404, 410):
                module.withdraw(db, asset, f'Removed from {name}.')
                return {**asset, 'status': 'hidden'}, f'“{asset["title"]}” has been removed from {name}.', False
            if not module.needs_details(asset):  # older details still stand
                return asset, None, False
            return asset, f'Could not read this entry from {name} right now: {exc}', False
        module.apply_detail(db, asset, record, reason)
        if record is None:
            return {**asset, 'status': 'hidden'}, f'“{asset["title"]}” is not available here: {reason}', False
        return catalog.get(db, asset['id']), None, False
    asset, problem = ensure_downloads(db, asset)
    return asset, problem, False


def ensure_contents(db, asset: dict) -> dict:
    """List what an entry's zips contain (range requests), for search, get and pick."""
    module = importer(asset['source'])
    if module is None or not hasattr(module, 'read_contents') or asset.get('status') != 'published':
        return asset
    updated = module.read_contents(asset)
    if updated is None:
        return asset
    with transaction(db):
        catalog.upsert(db, updated)
    return catalog.get(db, asset['id']) or updated


def ensure_downloads(db, asset: dict) -> tuple[dict, str | None]:
    """Fill in a lazily listed asset's download variants (Poly Haven)."""
    if asset.get('downloads') is not None:
        return asset, None
    module = importer(asset['source'])
    if module is None or not hasattr(module, 'fetch_downloads'):
        return asset, None
    try:
        variants, attributes = module.fetch_downloads(asset['source_id'], asset)
    except net.FetchError as exc:
        return asset, f'Could not list files from {credits.SOURCE_NAMES.get(asset["source"])} right now: {exc}'
    merged = {**(asset.get('attributes') or {}), **attributes}
    with transaction(db):
        db.execute('UPDATE assets SET downloads=?, downloads_fetched_at=?, attributes=? WHERE id=?',
                   (dumps(variants), now(), dumps(merged), asset['id']))
    return {**asset, 'downloads': variants, 'attributes': merged}, None


def defaults_for(asset: dict) -> list[str]:
    own = (asset.get('attributes') or {}).get('default_variant')  # chosen per entry (OpenGameArt)
    module = importer(asset['source'])
    table = getattr(module, 'DEFAULT_VARIANT', {}) if module else {}
    return ([own] if own else []) + table.get(asset['type'], [])


LIVE_PROBLEMS = (freesound.NotConnected, freesound.Rejected, freesound.Throttled, net.FetchError)
_STALE_HINTS = ('No CC0 sounds matched', 'No assets match')


def as_list(value) -> list[str]:
    """A list argument as sent by any agent runtime: a list, JSON text of a list, or comma-separated text."""
    if isinstance(value, str):
        text = value.strip()
        if text.startswith('['):
            try:
                value = json.loads(text)
            except ValueError:
                value = text.strip('[]').split(',')
        else:
            value = text.split(',')
    if not isinstance(value, (list, tuple)):
        return []
    return [str(item).strip().strip('"\'') for item in value if str(item).strip().strip('"\'')]


def find(db, asset_id: str) -> dict:
    asset = catalog.get(db, asset_id) if isinstance(asset_id, str) else None
    if asset is None and isinstance(asset_id, str) and asset_id.startswith('freesound:'):
        asset = freesound.sound(db, asset_id.split(':', 1)[1])
    if asset is None:
        raise NotFound(f'No asset with id “{asset_id}”. Search first and use a result’s id.')
    return asset


def search_assets(db, params: dict) -> dict:
    """Assets matching the query, plus the tools that could make or supply them."""
    result = _search_library(db, params)
    result['tools'] = _tools_for(db, result)
    return result


def _tools_for(db, result: dict) -> list[dict]:
    """Directory entries worth showing next to these results.

    Always when the query asks to make something; otherwise entries whose own
    words match, plus type-matched ones only when few assets fit.
    """
    interpreted = result.get('interpreted') or {}
    groups = [search._group(term) for term in interpreted.get('concepts') or []]
    wants_tool = interpreted.get('intent') == 'make'
    strong = sum(1 for r in result['results'] if (r.get('match') if r.get('match') is not None else 1) >= 1)
    makes = list(interpreted.get('type') or [])
    if wants_tool and not makes and result['results']:  # "generate a dragon": infer the kind from what matched
        kinds = [r['type'] for r in result['results'][:5]]
        makes = [max(set(kinds), key=kinds.count)]
    tools = resources.search(db, groups, makes=makes, limit=5 if wants_tool else 3)
    if wants_tool and not tools:
        tools = [t for t in resources.listing(db, kind='generator')][:5]
    if not wants_tool and strong >= 3:
        tools = [t for t in tools if t['matched_words']]
    if wants_tool and tools:
        result['notices'] = result['notices'] + ['Tools that can make this are listed with the results.']
    return tools


def _search_library(db, params: dict) -> dict:
    local = _search_local(db, params)
    interpreted = local['interpreted']
    types = [t for t in search._as_list(params.get('type')) if t] or interpreted.get('type') or []
    if not _live_allowed(interpreted):
        return local
    concepts = interpreted.get('concepts') or []
    options = {'sort': interpreted.get('sort'), 'limit': local['limit'], 'offset': local['offset'],
               'max_duration': interpreted.get('max_duration'), 'tags': search._as_list(params.get('tags'))}
    try:
        if types == ['sound']:
            return _merge_sounds(local, freesound.search(db, concepts, **options))
        live_total = freesound.count(db, concepts, max_duration=options['max_duration'])
        # With another type selected only the Sounds tab count changes; other facets describe that type.
        _add_sound_facets(local, live_total, type_only=bool(types))
        if local['total'] == 0 and live_total and not types:
            merged = _merge_sounds(local, freesound.search(db, concepts, **options))
            merged['interpreted']['type'] = ['sound']
            merged['notices'].append('Nothing else matched, so these are CC0 sounds from Freesound.')
            return merged
    except freesound.NotConnected as exc:
        if types == ['sound']:
            local['notices'] = [n for n in local['notices'] if not n.startswith(_STALE_HINTS)] + [str(exc)]
    except (freesound.Rejected, freesound.Throttled, net.FetchError) as exc:
        local['notices'].append(f'Freesound is unavailable: {exc}')
    return local


def _live_allowed(interpreted: dict) -> bool:
    """Freesound offers CC0 sounds only; skip it when the filters exclude that."""
    licenses = interpreted.get('license')
    sources = interpreted.get('source')
    formats = interpreted.get('format')
    return not ((licenses and 'CC0-1.0' not in licenses) or (sources and 'freesound' not in sources)
                or interpreted.get('style') or (formats and not set(formats) & {'ogg', 'mp3', 'wav'}))


def _merge_sounds(local: dict, live: dict) -> dict:
    """Local sounds from other sources first, then the live Freesound page."""
    facets = local.get('facets') or {}
    by_source = facets.get('source') or {}
    others = [c for c in local['results'] if c['source'] != 'freesound'] if local['offset'] == 0 else []
    other_total = sum(n for source, n in by_source.items() if source != 'freesound') if facets else len(others)
    seen = {c['id'] for c in others}
    results = others + [catalog.card(a) for a in live['assets'] if a['id'] not in seen]
    merged = {**local, 'results': results, 'total': other_total + live['total'],
              'next_offset': live['next_offset'], 'interpreted': dict(local['interpreted']),
              'notices': [n for n in local['notices'] if not n.startswith(_STALE_HINTS)]}
    if facets:
        _add_sound_facets(merged, live['total'])
    return merged


def _add_sound_facets(result: dict, live_total: int, type_only: bool = False) -> None:
    """Count Freesound matches in the type, source and licence facets."""
    facets = result.setdefault('facets', {})
    local_live = (facets.get('source') or {}).get('freesound', 0)  # pulled sounds, already counted
    types = facets.setdefault('type', {})
    types['sound'] = max(0, types.get('sound', 0) - (0 if type_only else local_live)) + live_total
    if type_only:
        return
    facets.setdefault('source', {})['freesound'] = live_total
    licences = facets.setdefault('license', {})
    licences['public-domain'] = max(0, licences.get('public-domain', 0) - local_live) + live_total


def _search_local(db, params: dict) -> dict:
    return search.search(
        db, params.get('query') or params.get('q') or '',
        type=params.get('type'), license=params.get('license'), source=params.get('source'),
        style=params.get('style'), tags=as_list(params.get('tags')) or None, category=params.get('category'),
        format=params.get('format'), min_resolution=params.get('min_resolution'),
        max_polycount=params.get('max_polycount'), max_duration=params.get('max_duration'),
        sort=params.get('sort'), limit=params.get('limit') or 24, offset=params.get('offset') or 0,
        facets=params.get('facets', True) is not False)


def probe_sizes(db, asset: dict) -> dict:
    """Ask the source for unknown download sizes once (a HEAD request), then remember them."""
    module = importer(asset['source'])
    if not hasattr(module, 'probe_sizes') or not any(v.get('size') is None for v in asset.get('downloads') or []):
        return asset
    variants = module.probe_sizes(asset)
    if variants and asset.get('origin') != 'live':
        with transaction(db):
            db.execute('UPDATE assets SET downloads=? WHERE id=?', (dumps(variants), asset['id']))
    return {**asset, 'downloads': variants} if variants else asset


def get_asset(db, asset_id: str, *, engine: str | None = None, with_related: bool = True,
              fetch: bool = True) -> dict:
    """One asset in full. `fetch` (agents) may read the source now; the UI only queues the read."""
    if isinstance(asset_id, str) and asset_id.startswith('tool:'):
        tool = resources.get(db, asset_id)
        if tool is None:
            raise NotFound(f'No tool or resource with id “{asset_id}”.')
        return tool
    asset = find(db, asset_id)
    asset, problem, pending = ensure_details(db, asset, fetch=fetch)
    if fetch and not pending and not problem:
        asset = ensure_contents(db, asset)
    asset = probe_sizes(db, asset)
    result = catalog.detail(db, asset, engine=engine)
    result['default_variant'] = _default_variant_id(asset)
    if pending:
        result['details_pending'] = True
    if problem:
        result['downloads_error'] = problem
    if with_related:
        result['related'] = catalog.related(db, asset)
    result['field_notes'] = resources.notes_for(db, asset['id'], 10)
    return result


def add_resource(db, record: dict, actor: dict | None = None, *, origin: str = 'agent') -> dict:
    """Add a tool or resource link to the directory (published, marked unreviewed)."""
    with transaction(db):
        outcome, resource_id = resources.upsert(db, record, origin=origin, actor=actor)
    entry = resources.get(db, resource_id)
    if outcome == 'exists':
        return {'outcome': 'already listed', 'resource': entry,
                'hint': 'This link is already in the directory; add what you learned with asset_commons_note.'}
    return {'outcome': 'added', 'resource': entry}


def add_note(db, target: str, text: str, outcome: str = 'tip', actor: dict | None = None) -> dict:
    """A field note on an asset or a directory entry, for the next agent."""
    if not isinstance(target, str) or not target:
        raise NotFound('id is required: an asset id or a tool:<id> from the directory.')
    if target.startswith('tool:'):
        if resources.get(db, target) is None:
            raise NotFound(f'No tool or resource with id “{target}”.')
    else:
        asset = find(db, target)
        if asset.get('origin') == 'live' and catalog.get(db, asset['id']) is None:
            with transaction(db):
                catalog.upsert(db, asset)  # keep the sound so its note has something to hang on
    return resources.add_note(db, target, text, outcome, actor)


def _default_variant_id(asset: dict) -> str | None:
    variants = asset.get('downloads') or []
    try:
        return download.choose_variant(asset, defaults_for(asset))['id'] if variants else None
    except download.DownloadError:
        return None


def download_asset(db, args: dict, actor: dict | None = None) -> dict:
    asset = find(db, args.get('id') or args.get('asset_id'))
    if asset.get('status') != 'published':
        raise download.DownloadError('This asset is not published (it may be pending review or hidden).')
    module = importer(asset['source'])
    asset, problem, pending = ensure_details(db, asset, fetch=True,
                                             max_age_days=getattr(module, 'DETAILS_MAX_AGE_DAYS', None))
    if problem:
        raise download.DownloadError(problem)
    if pending:
        raise download.DownloadError(f'“{asset["title"]}” is still being read from its source; try again in a '
                                     'minute.')
    outcome = download.run(asset, defaults_for(asset), args.get('dest_dir'), variant=args.get('variant'),
                           resolution=args.get('resolution'), fmt=args.get('format'),
                           folder=args.get('folder'), max_mb=args.get('max_mb') or 300,
                           overwrite=bool(args.get('overwrite')),
                           pick=as_list(args.get('pick')) or None)
    with transaction(db):
        if asset.get('origin') == 'live' and catalog.get(db, asset['id']) is None:
            catalog.upsert(db, asset)  # keep what was used, as provenance for credits
        if not outcome['reused']:
            db.execute('INSERT INTO pulls (asset_id, variant, dest, actor, bytes, at) VALUES (?,?,?,?,?,?)',
                       (asset['id'], outcome['variant']['id'], outcome['folder'], dumps(actor or {}),
                        outcome['bytes'], now()))
    engine = engine_id(args.get('engine'))
    detail = catalog.detail(db, asset, engine=engine)
    folder = Path(outcome['folder'])
    paths = [str(folder / f['path']) for f in outcome['files']]
    summary = {}
    if len(paths) > 25:  # an unpacked pack: list a sample and count files per folder
        folders: dict[str, int] = {}
        for f in outcome['files']:
            parts = Path(f['path']).parts
            key = '/'.join(parts[:2]) if len(parts) > 2 else (parts[0] if len(parts) > 1 else '.')
            folders[key] = folders.get(key, 0) + 1
        summary = {'file_count': len(paths), 'folders': folders,
                   'note': f'Showing 25 of {len(paths)} files; see the folders above.'}
    return {
        'asset': catalog.card(asset), 'variant': outcome['variant']['id'], 'folder': str(folder),
        'files': paths[:25], **summary, 'bytes': outcome['bytes'],
        'reused_existing_download': outcome['reused'],
        'license': detail['license_detail']['short'], 'attribution_required': detail['attribution_required'],
        'credit': detail['credit'], 'provenance_file': str(folder / download.PROVENANCE),
        'import_notes': detail['import_notes'],
        **({'source_notes': detail['source_notes']} if detail.get('source_notes') else {}),
    }


def credits_for(db, *, ids=None, directory: str | None = None, write: bool = False,
                title: str = 'Credits') -> dict:
    assets, missing = [], []
    for asset_id in ids or []:
        try:
            asset = find(db, asset_id)
        except (NotFound, *LIVE_PROBLEMS):
            asset = None
        (assets.append(asset) if asset else missing.append(asset_id))
    if directory:
        for record in download.scan(directory):
            asset = catalog.get(db, record['asset_id'])
            if asset:
                assets.append(asset)
            else:  # an asset no longer in this library: trust its provenance file
                license_id = (record.get('license') or {}).get('id') or 'CC0-1.0'
                assets.append({'id': record['asset_id'], 'title': record.get('title'),
                               'source': record.get('source'), 'source_url': record.get('source_url'),
                               'authors': record.get('authors') or [], 'license': license_id})
    text = credits.credits_markdown(assets, title=title)
    written = None
    if write:
        if not directory:
            raise download.DownloadError('write needs dir: the project folder to put CREDITS.md in.')
        root = download.resolve_dest(directory)
        target = root / 'CREDITS.md'
        if target.exists() and GENERATED_MARK not in target.read_text(errors='replace'):
            target = root / 'CREDITS.asset-commons.md'
        target.write_text(GENERATED_MARK + '\n' + text)
        written = str(target)
    needs = sum(1 for a in {a['id']: a for a in assets}.values() if credits.needs_credit(a))
    return {'markdown': text, 'assets': len({a['id'] for a in assets}), 'attribution_required': needs,
            'missing_ids': missing, 'written_to': written}


def sources_status(db, *, check: bool = False) -> dict:
    """Every source with its state; Freesound reports whether its key works."""
    from .sources import public as public_sources
    counts = catalog.stats(db)['by_source']
    synced = {row['id']: dict(row) for row in db.execute('SELECT * FROM sources')}
    sources = [{**source, 'assets': counts.get(source['id'], 0),
                'last_sync_at': (synced.get(source['id']) or {}).get('last_sync_at'),
                'last_status': (synced.get(source['id']) or {}).get('last_status')} for source in public_sources()]
    progress = crawl_progress(db)
    if progress:
        for source in sources:
            if source['id'] == 'opengameart':
                source['reading'] = progress
    state = {'connected': False, 'state': 'not-connected', 'cc0_sounds': None,
             'message': 'Not connected yet.'}
    try:
        key = freesound.read_key()
    except freesound.NotConnected:
        return {'sources': sources, 'freesound': state}
    try:
        total = freesound.count(db, [], key=key, fresh=check)
        state.update(connected=True, state='connected', cc0_sounds=total,
                     message=f'Connected · {total:,} CC0 sounds available')
    except freesound.Rejected as exc:
        state.update(state='rejected', message=str(exc))
    except freesound.Throttled as exc:
        state.update(connected=True, state='throttled', message=str(exc))
    except net.FetchError as exc:
        state.update(connected=True, state='unreachable', message=f'Freesound could not be reached: {exc}')
    return {'sources': sources, 'freesound': state}


def forget_freesound(db) -> dict:
    freesound.forget(db)
    return {'forgotten': True}


def overview(db) -> dict:
    from .sources import public as public_sources
    data = catalog.stats(db)
    data['tools'] = db.execute("SELECT COUNT(*) FROM resources WHERE status='published'").fetchone()[0]
    data['source_info'] = public_sources()
    data['engines'] = ENGINES
    progress = crawl_progress(db)
    if progress:
        data['reading'] = {'opengameart': progress}
        if progress['waiting'] and _stale(progress.get('updated_at'), 15):
            kick_sync(db)  # the job stopped (a restart?): pick the reading up again
    return data


def set_status(db, asset_id: str, status: str, actor: dict | None, note: str = '') -> dict:
    if status not in catalog.STATUSES:
        raise ValueError('Unknown status.')
    find(db, asset_id)
    with transaction(db):
        db.execute('UPDATE assets SET status=?, updated_at=? WHERE id=?', (status, now(), asset_id))
        db.execute('INSERT INTO moderation_events (asset_id, action, actor, note, at) VALUES (?,?,?,?,?)',
                   (asset_id, {'published': 'approved', 'hidden': 'hidden', 'rejected': 'rejected',
                               'pending': 'submitted'}[status], dumps(actor or {}), note[:500], now()))
    return {'id': asset_id, 'status': status}


def storage_bytes() -> int:
    root = Path(os.environ.get('APP_STORAGE_DIR', '.')) / 'catalog'
    return sum(p.stat().st_size for p in root.glob('*') if p.is_file())
